before:
  hooks:
    - go mod tidy
builds:
  -
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - ppc64
    goarm:
      - "7"

checksum:
    name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
