# EPGStationの設定
epg-station:
  host-name: "http://localhost:8888"

# Slack の設定
slack:
  # Slack の API キー
  api-key: "YOUR_API_KEY"

  # 投稿するチャンネル
  # コマンド側で指定がない場合はこの値が使われる
  channel: "CHANNEL_ID"

# 各コマンドの設定
commands:
  reserve-new-addition: &pre-command-default
    # 通知を実行するかの設定
    # EPGStation の config.json にコマンドの設定はしてあるけど, 通知を無効化したいときなどは false にする
    enable: true

    # Slack で使用されるメッセージ
    # Box Kit のヘッダーセクションで使われ, 通知の際はこのメッセージが表示される
    # 絵文字も使える
    # 変数を埋め込むことも可能
    # EPGStation で設定される環境変数により作られる struct が渡される
    # struct の内容は env.go を参照
    message: ":new: {{ .ChannelName }} で {{ .Name }} の録画予約が新規追加されました"

    # 環境変数を表示するフィールドの設定
    # message と同様にフォーマットを自由に変えられる
    # Slack API の制限で, フィールドは10個までしか設定できないので注意
    fields-section:
      - title: "ProgramID"
        template: "{{ .ProgramID }}"

      - title: "ChannelType, ChannelID, ChannelName"
        template: "{{ .ChannelType }}, {{ .ChannelID }}, {{ .ChannelName }}"

      - title: "StartAt, EndAt, Duration"
        template: "{{ .StartAt }}, {{ .EndAt }}, {{ .Duration }}"

      - title: "Name"
        template: "{{ .Name }}"

      - title: "Description"
        template: "{{ .Description }}"

      - title: "Extended"
        template: "{{ .Extended }}"

    # 特定のコマンドのみ別チャンネルに振り分けたい時に指定する.
    # プロパティがない場合は slack の channel が使われる
    channel: "CHANNEL_ID"

  reserve-update:
    <<: *pre-command-default
    enable: true
    message: ":up: {{ .ChannelName }} で {{ .Name }} の録画情報が更新されました"

  reserve-deleted:
    <<: *pre-command-default
    enable: true
    message: ":black_square_for_stop: {{ .ChannelName }} で {{ .Name }} の録画予約が削除されました"

  recording-pre-start:
    <<: *pre-command-default
    enable: true
    message: ":soon: {{ .ChannelName }} で {{ .Name }} の録画準備が開始しました"

  recording-prep-rec-failed:
    <<: *pre-command-default
    enable: true
    message: ":x: {{ .ChannelName }} で {{ .Name }} の録画準備に失敗しました"

  recording-start: &rec-command-default
    enable: true
    message: ":arrow_forward: {{ .ChannelName }} で {{ .Name }} の録画が開始しました"
    fields-section:
      - title: "RecordedID, ProgramID"
        template: "{{ .RecordedID }}, {{ .ProgramID }}"

      - title: "ChannelType, ChannelID, ChannelName"
        template: "{{ .ChannelType }}, {{ .ChannelID }}, {{ .ChannelName }}"

      - title: "StartAt, EndAt, Duration"
        template: "{{ .StartAt }}, {{ .EndAt }}, {{ .Duration }}"

      - title: "Name"
        template: "{{ .Name }}"

      - title: "Description"
        template: "{{ .Description }}"

      - title: "Extended"
        template: "{{ .Extended }}"

      - title: "RecPath"
        template: "{{ .RecPath }}"

      - title: "LogPath"
        template: "{{ .LogPath }}"

  recording-finish:
    <<: *rec-command-default
    enable: true
    message: ":white_check_mark: {{ .ChannelName }} で {{ .Name }} の録画が終了しました"

  recording-failed:
    <<: *rec-command-default
    enable: true
    message: ":x: {{ .ChannelName }} で {{ .Name }} の録画中にエラーが発生しました"

  encoding-finish:
    enable: true
    message: ":white_check_mark: {{ .HalfWidthChannelName }} の {{ .HalfWidthName }} のエンコードが終了しました"
    fields-section:
      - title: "RecordedID, VideoFileID"
        template: "{{ .RecordedID }}, {{ .VideoFileID }}"

      - title: "OutputPath"
        template: "{{ .OutputPath }}"

      - title: "Mode"
        template: "{{ .Mode }}"

      - title: "ChannelID, HalfWidthChannelName"
        template: "{{ .ChannelID }}, {{ .HalfWidthChannelName }}"

      - title: "HalfWidthName"
        template: "{{ .HalfWidthName }}"

      - title: "HalfWidthDescription"
        template: "{{ .HalfWidthDescription }}"

      - title: "HalfWidthExtended"
        template: "{{ .HalfWidthExtended }}"
