name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.x
        package:
          - .
          - ./pkg/app
          - ./pkg/command
          - ./pkg/config
          - ./pkg/env

    steps:
      -   uses: actions/checkout@v4

      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: go vet
        run: go vet ${{ matrix.package }}

      - name: go test
        run: go test -v ${{ matrix.package }}
