name: Test

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest ]
                go-version: [ 1.x ]

        steps:
            -   uses: actions/checkout@v1

            -   name: Use Go ${{ matrix.go-version }}
                uses: actions/setup-go@v1
                with:
                    go-version: ${{ matrix.go-version }}

            -   name: go vet
                run: go vet

            -   name: test command
                run: go test ./pkg/command/ -v

            -   name: test config
                run: go test ./pkg/config/ -v

            -   name: test env
                run: go test ./pkg/env/ -v
