name: Go CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - run: go get golang.org/x/lint/golint

      - name:
        run: golint -set_exit_status
        env:
          CI: true

      - name: Slack Notification
        uses: homoluctus/slatify@v1.5
        if: always()
        with:
          job_name: '*${{ github.workflow }}*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
